ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.nxos.nxos
ansible_user: admin
ansible_password: decisiontek12.
ansible_become: yes
ansible_become_method: enable
ansible_become_password: decisiontek12.
