---
- hosts: spine
  tasks:
    - name: Gather interfaces resource and minimal legacy facts
      cisco.nxos.nxos_facts:
        gather_subset: min
        gather_network_resources: interfaces
    
    - name: Ensure Default services are enabled
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
      with_items:
        - "{{ features }}"
    
    - name: Override device configuration of all interfaces with provided configuration
      cisco.nxos.nxos_interfaces:
        config:
        - name: Ethernet1/1
          description: Configured by Ansible Network
          enabled: true
        - name: Ethernet1/2
          description: Configured by Ansible Network
          enabled: true
        state: overridden
    
    - name: Configure LACP between spines switches
      cisco.nxos.nxos_lag_interfaces:
        config:
        - name: "{{ item.name }}"
          members:
            - member: "{{ item.member }}"
              mode: "{{ item.mode }}"
        state: replaced
      with_items:
        - "{{ portchannel }}"
    
        
